# Generated by Django 4.2 on 2023-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_brand_category_alter_product_name_product_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="ratings", field=models.IntegerField(),
        ),
    ]
