# Generated by Django 4.2 on 2023-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product", name="colors", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
