# Generated by Django 4.2 on 2023-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="account_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="cvv",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="expiry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ifsc",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
