# Generated by Django 4.2 on 2023-04-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="house",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address", name="pincode", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
