# Generated by Django 4.2 on 2023-04-28 09:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_address_city_alter_address_house_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
    ]
